import { mkdirSync } from 'node:fs';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * All paths are resolved from environment variables first, then from the
 * location of this file. Nothing depends on the current working directory,
 * because MCP clients (Claude Desktop, Claude Code, Cursor) start the server
 * from different directories.
 *
 * This file lives at apps/server/{src|dist}/utils/config.(ts|js),
 * so both the source and the built output are the same depth below the server package.
 */
const thisDir = dirname(fileURLToPath(import.meta.url));
const serverPackageDir = resolve(thisDir, '..', '..');
const repoRootDir = resolve(serverPackageDir, '..', '..');

export const APP_NAME = 'vibe-context';
export const APP_VERSION = '0.1.0';

function readPathEnv(name: string): string | undefined {
  const value = process.env[name]?.trim();
  if (!value) return undefined;
  return isAbsolute(value) ? value : resolve(process.cwd(), value);
}

/** Directory for local data (SQLite DB). Default: <repo>/data */
export function resolveDataDir(): string {
  return readPathEnv('VIBE_CONTEXT_DATA_DIR') ?? join(repoRootDir, 'data');
}

/** SQLite file path. Default: <data dir>/vibe-context.db */
export function resolveDatabasePath(): string {
  return readPathEnv('VIBE_CONTEXT_DB_PATH') ?? join(resolveDataDir(), 'vibe-context.db');
}

/** SQL migrations generated by drizzle-kit. Shipped next to the server package. */
export function resolveMigrationsDir(): string {
  return readPathEnv('VIBE_CONTEXT_MIGRATIONS_DIR') ?? join(serverPackageDir, 'drizzle');
}

export interface AppConfig {
  databasePath: string;
  migrationsDir: string;
}

export function loadConfig(): AppConfig {
  const databasePath = resolveDatabasePath();
  mkdirSync(dirname(databasePath), { recursive: true });
  return {
    databasePath,
    migrationsDir: resolveMigrationsDir(),
  };
}
